#!/usr/bin/env python3
"""Assemble ap.html from the source parts.

The three fonts are spliced in as base64 @font-face rules so the game keeps
working offline and over WhatsApp, with no network request at all.

    python build.py
"""
import pathlib, sys

HERE = pathlib.Path(__file__).parent
PARTS = ['_p1.html', '_p2.html', '_p3.js', '_p4.js', '_p5.js', '_p5b.js', '_p5c.js',
         '_p6.js', '_p7.js']
OUT = HERE / 'ap.html'


def main():
    missing = [p for p in PARTS + ['_fonts.css'] if not (HERE / p).exists()]
    if missing:
        sys.exit('missing source parts: ' + ', '.join(missing))

    fonts = (HERE / '_fonts.css').read_text(encoding='utf-8').strip()
    chunks = [(HERE / p).read_text(encoding='utf-8') for p in PARTS]
    html = '\n'.join(chunks) + '\n</script>\n</body>\n</html>\n'

    if '__FONTS__' not in html:
        sys.exit('__FONTS__ placeholder not found')
    html = html.replace('__FONTS__', fonts)
    banner = ('<!-- GENERATED by build.py from _p1.html … _p7.js + _fonts.css.\n'
              '     Edit those, then run: python build.py\n'
              '     Changes made directly in this file will be overwritten. -->\n')
    html = html.replace('<!doctype html>\n', '<!doctype html>\n' + banner, 1)

    OUT.write_text(html, encoding='utf-8')
    kb = OUT.stat().st_size / 1024
    print('wrote %s  (%.0f KB)' % (OUT.name, kb))

    # cheap sanity checks that have bitten before
    for needle in ['<title>', 'a + (n', 'ap-sw.js', 'globalThis.__ap']:
        if needle not in html:
            sys.exit('sanity check failed: %r missing' % needle)


if __name__ == '__main__':
    main()
